#-------------------------------
# General Site Settings
title: Abhigya's BlogSpot
logo: 'https://avatars.githubusercontent.com/u/71663979?v=4'
description: A computer enthusiasts excited to learn about tech and share knowledge.
baseurl: ""
url: "https://abhigya.me"


#-------------------------------
# Author Settings
author:
  name: Abhigya Krishna
  avatar: 'https://avatars.githubusercontent.com/u/71663979?v=4'


#-------------------------------
# Hero Settings
hero:
  title: Abhigya Krishna
  description: Backend, Cloud and Devops Engineer
  image: '/images/home-background.webp'


#-------------------------------
# Contact Settings
# https://formspree.io/
contact:
  email: abhigyakrishna21@gmail.com
  description: Have any question, suggestion or just want to say hi? Feel free to reach out to me.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
  - { icon: "ion-logo-github", link: "https://github.com/AbhigyaKrishna" }
  - { icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/abhigya-krishna" }
  - { icon: "ion-logo-twitter", link: "https://twitter.com/AbhigyaKr1shna" }


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: abhigya


#-------------------------------
# Google Analytics
google-analytics: G-RRHN7XMFF8


#-------------------------------
# Newsletter
mailchimp: disable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-tagging

kramdown:
  input: GFM
  footnote_backlink: "&#8617;&#xfe0e;"

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed